### ISSUE TITLE
Segfault on start

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#45]
The lastest commit broke something. I recompiled with `-O0 -fsanitize` and here's the ASAN output:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==14879==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x55e1cff14107 bp 0x7fff541e66e0 sp 0x7fff541e66c0 T0)
==14879==The signal is caused by a READ memory access.
==14879==Hint: this fault was caused by a dereference of a high value address (see register values below).  Dissassemble the provided pc to learn which register was used.
    #0 0x55e1cff14107 in SourceFindEndOfBlock() /home/aolo2/Documents/bin/gf/gf2.cpp:322
    #1 0x55e1cff18d61 in DisplaySetPosition /home/aolo2/Documents/bin/gf/windows.cpp:83
    #2 0x55e1cff2cd62 in WindowMessage(UIElement*, UIMessage, int, void*) /home/aolo2/Documents/bin/gf/gf2.cpp:1186
    #3 0x55e1cfee9bae in UIElementMessage /home/aolo2/Documents/bin/gf/luigi.h:1367
    #4 0x55e1cff105a6 in _UIProcessEvent /home/aolo2/Documents/bin/gf/luigi.h:4542
    #5 0x55e1cff126db in _UIMessageLoopSingle /home/aolo2/Documents/bin/gf/luigi.h:4696
    #6 0x55e1cff0bd51 in UIMessageLoop /home/aolo2/Documents/bin/gf/luigi.h:4207
    #7 0x55e1cff2dc09 in main /home/aolo2/Documents/bin/gf/gf2.cpp:1317
    #8 0x7eff93febd09 in __libc_start_main ../csu/libc-start.c:308
    #9 0x55e1cfee3959 in _start (/home/aolo2/Documents/bin/gf/gf2+0xc959)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/aolo2/Documents/bin/gf/gf2.cpp:322 in SourceFindEndOfBlock()
==14879==ABORTING
```

p.s. congrats on 100 stars! :D

**Comment by nakst** [comment]
Fixed in d7e50a9.
